[tool.black]
line-length = 100
target-version = ["py313"]

[tool.isort]
profile = "black"
known_first_party = [
  "server",
  "cli",
  "utils",
  "core",
  "platform",
  "analysis",
  "devices",
  "app_config",
  "storage",
  "orchestrator",
  "workers",
]
