[tool.black]
line-length = 100
target-version = ["py313"]

[tool.isort]
profile = "black"
py_version = 313
known_first_party = [
  "server",
  "cli",
  "utils",
  "core",
  "platform",
  "analysis",
  "storage",
]
